name = "TraeBlain.com 2023"
license = "Unlicense"
licenselink = "https://unlicense.org"
description = "The Theme to TraeBlain.com circa 2023"
homepage = "https://traeblain.com/"
tags = ["clean", "hero", "types"]
features = ["Has multiple post types: blog, quotes, links, video, status, images."]
min_version = "0.109.0"
demosite = "https://traeblain.com/"

[author]
  name = "Trae Blain"
  homepage = "https://traeblain.com/"

