backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
media_library:
  name: cloudinary
  config:
    cloud_name: dixwznarl
    api_key: 633573216924142
site_url: https://traeblain.com
logo_url: https://res.cloudinary.com/dixwznarl/image/upload/v1480537358/tbcom/tbmonogram.svg
editor:
  preview: true
view_filters:
  - label: Drafts
    field: draft
    pattern: true
view_groups:
  - label: Year
    field: date
    pattern: \d{4}
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'        
      - label: 'Draft?'
        name: 'draft'
        widget: 'boolean'
        default: true
      - label: 'Description/Summary'
        name: 'description'
        widget: 'string'
        required: false
      - label: 'Images'
        name: 'images'
        widget: 'image'
        media_library: 
          config:
            multiple: true
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        allow_add: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Script'
        name: 'script'
        widget: 'string'
        required: false
  - name: 'image'
    label: 'Image'
    folder: 'content/blog/image'
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        required: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'        
      - label: 'Draft?'
        name: 'draft'
        widget: 'boolean'
        default: true
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'image'
      - label: 'Images'
        name: 'images'
        widget: 'image'
        media_library: 
          config:
            multiple: true
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - name: 'link'
    label: 'Link'
    folder: 'content/blog/link'
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'        
      - label: 'Draft?'
        name: 'draft'
        widget: 'boolean'
        default: true
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'link'
      - label: 'Source'
        name: 'source'
        widget: 'string'
      - label: 'Images'
        name: 'images'
        widget: 'image'
        media_library: 
          config:
            multiple: true
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - name: 'quote'
    label: 'Quote'
    folder: 'content/blog/quote'
    create: true
    slug: '{{fields.slug}}'
    summary: "{{body}} -- {{cite | upper}}"
    fields:
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'        
      - label: 'Draft?'
        name: 'draft'
        widget: 'boolean'
        default: true
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'quote'
      - label: 'Citation'
        name: 'cite'
        widget: 'string'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - name: 'status'
    label: 'Status'
    folder: 'content/blog/status'
    create: true
    slug: '{{fields.slug}}'
    summary: "{{emoji}} {{body}}"
    fields:
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'  
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'status'
      - label: 'Source'
        name: 'source'
        widget: 'string'
        required: false
      - label: 'Emoji'
        name: 'emoji'
        widget: 'string'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - name: 'video'
    label: 'Video'
    folder: 'content/blog/video'
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'        
      - label: 'Draft?'
        name: 'draft'
        widget: 'boolean'
        default: true
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'video'
      - label: 'Source'
        name: 'source'
        widget: 'string'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
